rule greyware_tools
{
    strings:
        
        $string1_whoami_greyware_tool_keyword = " -exec bypass -nop -c whoami" nocase ascii wide
        $string2_whoami_greyware_tool_keyword = "whoami /all" nocase ascii wide
        $string3_whoami_greyware_tool_keyword = "whoami /domain" nocase ascii wide
        $string4_whoami_greyware_tool_keyword = "whoami /groups" nocase ascii wide
        $string5_whoami_greyware_tool_keyword = "whoami /priv" nocase ascii wide
        $string6_whoami_greyware_tool_keyword = "whoami" nocase ascii wide
        $string7_whoami_greyware_tool_keyword = /whoami\.exe.{0,100}\s\/groups/ nocase ascii wide
       
        $string1_ScreenConnect_greyware_tool_keyword = /\:8040\/SetupWizard\.aspx/ nocase ascii wide
        $string2_ScreenConnect_greyware_tool_keyword = /\\CurrentControlSet\\Control\\SafeBoot\\Network\\ScreenConnect\sClient\s\(/ nocase ascii wide
        $string3_ScreenConnect_greyware_tool_keyword = /\\CurrentControlSet\\Services\\ScreenConnect\s/ nocase ascii wide
        $string4_ScreenConnect_greyware_tool_keyword = /\\Documents\\ConnectWiseControl\\Files/ nocase ascii wide
        $string5_ScreenConnect_greyware_tool_keyword = /\\InventoryApplicationFile\\screenconnect\.cl/ nocase ascii wide
        $string6_ScreenConnect_greyware_tool_keyword = /\\InventoryApplicationFile\\screenconnect\.wi/ nocase ascii wide
        $string7_ScreenConnect_greyware_tool_keyword = /\\ScreenConnect\sClient\s\(/ nocase ascii wide
        $string8_ScreenConnect_greyware_tool_keyword = /\\ScreenConnect\.Client\.exe/ nocase ascii wide
        $string9_ScreenConnect_greyware_tool_keyword = /\\ScreenConnect\.ClientService\.exe/ nocase ascii wide
        $string10_ScreenConnect_greyware_tool_keyword = /\\ScreenConnect\.ClientSetup\.exe/ nocase ascii wide
        $string11_ScreenConnect_greyware_tool_keyword = /\\ScreenConnect\.Core\.dll/ nocase ascii wide
        $string12_ScreenConnect_greyware_tool_keyword = /\\ScreenConnect\.InstallerActions\.dll/ nocase ascii wide
        $string13_ScreenConnect_greyware_tool_keyword = /\\ScreenConnect\.Windows\.dll/ nocase ascii wide
        $string14_ScreenConnect_greyware_tool_keyword = /\\ScreenConnect\.WindowsBackstageShell\.exe/ nocase ascii wide
        $string15_ScreenConnect_greyware_tool_keyword = /\\ScreenConnect\.WindowsClient\.exe/ nocase ascii wide
        $string16_ScreenConnect_greyware_tool_keyword = /\\ScreenConnect\\Bin\\/ nocase ascii wide
        $string17_ScreenConnect_greyware_tool_keyword = /\\TEMP\\ScreenConnect\\.{0,100}\.ps1/ nocase ascii wide
        $string18_ScreenConnect_greyware_tool_keyword = /\\Temp\\ScreenConnect\\.{0,100}\\setup\.msi/ nocase ascii wide
        $string19_ScreenConnect_greyware_tool_keyword = /\\Windows\\Temp\\ScreenConnect\\.{0,100}\.cmd/ nocase ascii wide
        $string20_ScreenConnect_greyware_tool_keyword = /\\Windows\\Temp\\ScreenConnect\\.{0,100}\.ps1/ nocase ascii wide
        $string21_ScreenConnect_greyware_tool_keyword = "<Data>ScreenConnect Software</Data>" nocase ascii wide
        $string22_ScreenConnect_greyware_tool_keyword = "<Provider Name='ScreenConnect Security Manager'/>" nocase ascii wide
        $string23_ScreenConnect_greyware_tool_keyword = "<Provider Name='ScreenConnect Web Server'/>" nocase ascii wide
        $string24_ScreenConnect_greyware_tool_keyword = /cmd\.exe.{0,100}\\TEMP\\ScreenConnect\\.{0,100}\.cmd/ nocase ascii wide
        $string25_ScreenConnect_greyware_tool_keyword = /https\:\/\/.{0,100}\.screenconnect\.com\/Bin\/.{0,100}\.exe/ nocase ascii wide
        $string26_ScreenConnect_greyware_tool_keyword = /https\:\/\/.{0,100}\.screenconnect\.com\/Host/ nocase ascii wide
        $string27_ScreenConnect_greyware_tool_keyword = /https\:\/\/cloud\.screenconnect\.com\/\#\/trialtoinstance\?cookieValue\=/ nocase ascii wide
        $string28_ScreenConnect_greyware_tool_keyword = /Program\sFiles\s\(x86\)\\ScreenConnect\sClient/ nocase ascii wide
        $string29_ScreenConnect_greyware_tool_keyword = /\-relay\.screenconnect\.com/ nocase ascii wide
        $string30_ScreenConnect_greyware_tool_keyword = "ScreenConnect Software" nocase ascii wide
        $string31_ScreenConnect_greyware_tool_keyword = /ScreenConnect\.Client\.dll/ nocase ascii wide
        $string32_ScreenConnect_greyware_tool_keyword = /ScreenConnect\.Client\.exe\.jar/ nocase ascii wide
        $string33_ScreenConnect_greyware_tool_keyword = /ScreenConnect\.ClientService\.dll/ nocase ascii wide
        $string34_ScreenConnect_greyware_tool_keyword = /ScreenConnect\.ClientService\.exe/ nocase ascii wide
        $string35_ScreenConnect_greyware_tool_keyword = /ScreenConnect\.ClientSetup\.exe/ nocase ascii wide
        $string36_ScreenConnect_greyware_tool_keyword = /SCREENCONNECT\.CLIENTSETUP\.EXE\-.{0,100}\.pf/ nocase ascii wide
        $string37_ScreenConnect_greyware_tool_keyword = /ScreenConnect\.ClientUninstall\.vbs/ nocase ascii wide
        $string38_ScreenConnect_greyware_tool_keyword = /ScreenConnect\.Core\.pdb/ nocase ascii wide
        $string39_ScreenConnect_greyware_tool_keyword = /ScreenConnect\.Server\.dll/ nocase ascii wide
        $string40_ScreenConnect_greyware_tool_keyword = /ScreenConnect\.Service\.exe/ nocase ascii wide
        $string41_ScreenConnect_greyware_tool_keyword = /SCREENCONNECT\.SERVICE\.EXE\-.{0,100}\.pf/ nocase ascii wide
        $string42_ScreenConnect_greyware_tool_keyword = /ScreenConnect\.WindowsBackstageShell\.exe/ nocase ascii wide
        $string43_ScreenConnect_greyware_tool_keyword = /SCREENCONNECT\.WINDOWSCLIENT\..{0,100}\.pf/ nocase ascii wide
        $string44_ScreenConnect_greyware_tool_keyword = /ScreenConnect\.WindowsClient\.exe/ nocase ascii wide
        $string45_ScreenConnect_greyware_tool_keyword = /ScreenConnect\.WindowsInstaller\.dll/ nocase ascii wide
        $string46_ScreenConnect_greyware_tool_keyword = /ScreenConnect_.{0,100}_Release\.msi/ nocase ascii wide
        $string47_ScreenConnect_greyware_tool_keyword = /ScreenConnect_.{0,100}_Release\.tar\.gz/ nocase ascii wide
        $string48_ScreenConnect_greyware_tool_keyword = /ScreenConnect_.{0,100}_Release\.zip/ nocase ascii wide
        $string49_ScreenConnect_greyware_tool_keyword = /ScreenConnectClientNetworkDeployer\.exe/ nocase ascii wide
        $string50_ScreenConnect_greyware_tool_keyword = /server.{0,100}\-relay\.screenconnect\.com/ nocase ascii wide
        $string51_ScreenConnect_greyware_tool_keyword = /\-web\.screenconnect\.com/ nocase ascii wide
       
        $string1_Quasar_greyware_tool_keyword = " CN=Quasar Server CA" nocase ascii wide
        $string2_Quasar_greyware_tool_keyword = /\/Quasar\.git/ nocase ascii wide
        $string3_Quasar_greyware_tool_keyword = /\/Quasar\.v.{0,100}\.zip/ nocase ascii wide
        $string4_Quasar_greyware_tool_keyword = "/Quasar/releases" nocase ascii wide
        $string5_Quasar_greyware_tool_keyword = /\\appdata\\roaming\\.{0,100}\'DestPort\'\>4782\<\/Data\>/ nocase ascii wide
        $string6_Quasar_greyware_tool_keyword = /\\CurrentVersion\\Run\\Quasar\sClient\sStartup/ nocase ascii wide
        $string7_Quasar_greyware_tool_keyword = /\\Prefetch\\QUASAR\.EXE/ nocase ascii wide
        $string8_Quasar_greyware_tool_keyword = /\\Program\sFiles\\SubDir\\Client\.exe/ nocase ascii wide
        $string9_Quasar_greyware_tool_keyword = /\\Quasar\.Client\\/ nocase ascii wide
        $string10_Quasar_greyware_tool_keyword = /\\Quasar\.Common\\.{0,100}\.cs/ nocase ascii wide
        $string11_Quasar_greyware_tool_keyword = /\\quasar\.p12/ nocase ascii wide
        $string12_Quasar_greyware_tool_keyword = /\\Quasar\.v.{0,100}\.zip/ nocase ascii wide
        $string13_Quasar_greyware_tool_keyword = /\\Quasar\-master/ nocase ascii wide
        $string14_Quasar_greyware_tool_keyword = /\\Users\\mthcht\\AppData\\Roaming\\SubDir\\Client\.exe/ nocase ascii wide
        $string15_Quasar_greyware_tool_keyword = /\\Windows\\system32\\SubDir\\Client\.exe/ nocase ascii wide
        $string16_Quasar_greyware_tool_keyword = "14CA405B-8BAC-48AB-9FBA-8FB5DF88FD0D" nocase ascii wide
        $string17_Quasar_greyware_tool_keyword = "32A2A734-7429-47E6-A362-E344A19C0D85" nocase ascii wide
        $string18_Quasar_greyware_tool_keyword = "9F5CF56A-DDB2-4F40-AB99-2A1DC47588E1" nocase ascii wide
        $string19_Quasar_greyware_tool_keyword = /Backdoor\.Quasar/ nocase ascii wide
        $string20_Quasar_greyware_tool_keyword = "C7C363BA-E5B6-4E18-9224-39BC8DA73172" nocase ascii wide
        $string21_Quasar_greyware_tool_keyword = "CFCD0759E20F29C399C9D4210BE614E4E020BEE8" nocase ascii wide
        $string22_Quasar_greyware_tool_keyword = "localhost:4782" nocase ascii wide
        $string23_Quasar_greyware_tool_keyword = /namespace\sQuasar\.Client/ nocase ascii wide
        $string24_Quasar_greyware_tool_keyword = /namespace\sQuasar\.Server/ nocase ascii wide
        $string25_Quasar_greyware_tool_keyword = "ping -n 10 localhost > nul" nocase ascii wide
        $string26_Quasar_greyware_tool_keyword = "Quasar Client Startup" nocase ascii wide
        $string27_Quasar_greyware_tool_keyword = /Quasar\sv.{0,100}\\Client\-built\.exe/ nocase ascii wide
        $string28_Quasar_greyware_tool_keyword = /Quasar\.Client\./ nocase ascii wide
        $string29_Quasar_greyware_tool_keyword = /Quasar\.Common\.Tests\\/ nocase ascii wide
        $string30_Quasar_greyware_tool_keyword = /Quasar\.exe/ nocase ascii wide
        $string31_Quasar_greyware_tool_keyword = /Quasar\.Server/ nocase ascii wide
        $string32_Quasar_greyware_tool_keyword = /Quasar\.Server\\Program\.cs/ nocase ascii wide
        $string33_Quasar_greyware_tool_keyword = /Quasar\.sln/ nocase ascii wide
        $string34_Quasar_greyware_tool_keyword = /Quasar\.v1\.4\.1\.zip/ nocase ascii wide
        $string35_Quasar_greyware_tool_keyword = "quasar/Quasar" nocase ascii wide
        $string36_Quasar_greyware_tool_keyword = /Quasar\-master\.zip/ nocase ascii wide
        $string37_Quasar_greyware_tool_keyword = "QuasarRAT" nocase ascii wide
        $string38_Quasar_greyware_tool_keyword = "ylAo2kAlUS2kYkala!" nocase ascii wide
       
        $string1_telegram_greyware_tool_keyword = /\\AppData\\Roaming\\Telegram\sDesktop\\tdata/ nocase ascii wide
        $string2_telegram_greyware_tool_keyword = /api\.telegram\.org/ nocase ascii wide
        
        $string1_scp_greyware_tool_keyword = /scp\s.{0,100}\s.{0,100}\@.{0,100}\:/ nocase ascii wide
        $string2_scp_greyware_tool_keyword = /scp\s.{0,100}\@.{0,100}\:.{0,100}\s/ nocase ascii wide
        
        $string1_ngrok_greyware_tool_keyword = /\.ngrok\.me/ nocase ascii wide
        $string2_ngrok_greyware_tool_keyword = /\/ngrok\.exe/ nocase ascii wide
        $string3_ngrok_greyware_tool_keyword = /\/ngrok\.git/ nocase ascii wide
        $string4_ngrok_greyware_tool_keyword = /\/ngrok\.go/ nocase ascii wide
        $string5_ngrok_greyware_tool_keyword = /\/ngrok\.log/ nocase ascii wide
        $string6_ngrok_greyware_tool_keyword = /\/ngrokd\.go/ nocase ascii wide
        $string7_ngrok_greyware_tool_keyword = /\/ngrokroot\.crt/ nocase ascii wide
        $string8_ngrok_greyware_tool_keyword = /\\ngrok\.exe/ nocase ascii wide
        $string9_ngrok_greyware_tool_keyword = /\\ngrok\.go/ nocase ascii wide
        $string10_ngrok_greyware_tool_keyword = /\\ngrok\.log/ nocase ascii wide
        $string11_ngrok_greyware_tool_keyword = /\\ngrokd\.go/ nocase ascii wide
        $string12_ngrok_greyware_tool_keyword = "6abfc342f0a659066c8b42999510ccc3592b499569c2e7af37470a445a2e3560" nocase ascii wide
        $string13_ngrok_greyware_tool_keyword = "fe9dd722a085bce94fe2403f8d02e20becf0f0faa019d0789fadf35b66611a46" nocase ascii wide
        $string14_ngrok_greyware_tool_keyword = /http\:\/\/.{0,100}\.ngrok\.io/ nocase ascii wide
        $string15_ngrok_greyware_tool_keyword = /http\:\/\/127\.0\.0\.1\:4040\/api\/tunnels/ nocase ascii wide
        $string16_ngrok_greyware_tool_keyword = /https\:\/\/.{0,100}\.ngrok\.io/ nocase ascii wide
        $string17_ngrok_greyware_tool_keyword = "inconshreveable/ngrok" nocase ascii wide
        $string18_ngrok_greyware_tool_keyword = /LHOST\=0\.tcp\.ngrok\.io/ nocase ascii wide
        $string19_ngrok_greyware_tool_keyword = /Mozilla\/5\.0\s\(compatible\;\sngrok\)/ nocase ascii wide
        $string20_ngrok_greyware_tool_keyword = "ngrok tcp " nocase ascii wide
        $string21_ngrok_greyware_tool_keyword = /ngrok\,\sInc\./ nocase ascii wide
        $string22_ngrok_greyware_tool_keyword = /ngrokd\.ngrok\.com/ nocase ascii wide
        $string23_ngrok_greyware_tool_keyword = /tcp\:\/\/0\.tcp\.ngrok\.io\:/ nocase ascii wide
        $string24_ngrok_greyware_tool_keyword = /tunnel\.ap\.ngrok\.com/ nocase ascii wide
        $string25_ngrok_greyware_tool_keyword = /tunnel\.au\.ngrok\.com/ nocase ascii wide
        $string26_ngrok_greyware_tool_keyword = /tunnel\.eu\.ngrok\.com/ nocase ascii wide
        $string27_ngrok_greyware_tool_keyword = /tunnel\.in\.ngrok\.com/ nocase ascii wide
        $string28_ngrok_greyware_tool_keyword = /tunnel\.jp\.ngrok\.com/ nocase ascii wide
        $string29_ngrok_greyware_tool_keyword = /tunnel\.sa\.ngrok\.com/ nocase ascii wide
        $string30_ngrok_greyware_tool_keyword = /tunnel\.us\.ngrok\.com/ nocase ascii wide
        
        $string1_rdpwrap_greyware_tool_keyword = /\sRDPWInst\.exe/ nocase ascii wide
        $string2_rdpwrap_greyware_tool_keyword = /\srdpwrap\.dll/ nocase ascii wide
        $string3_rdpwrap_greyware_tool_keyword = "\"%~dp0RDPWInst\" -i -o" nocase ascii wide
        $string4_rdpwrap_greyware_tool_keyword = /\%\~dp0RDPWInst\.exe/ nocase ascii wide
        $string5_rdpwrap_greyware_tool_keyword = /\/RDPWInst\.exe/ nocase ascii wide
        $string6_rdpwrap_greyware_tool_keyword = /\/RDPWInst\-v.{0,100}\.msi/ nocase ascii wide
        $string7_rdpwrap_greyware_tool_keyword = /\/rdpwrap\.dll/ nocase ascii wide
        $string8_rdpwrap_greyware_tool_keyword = /\/rdpwrap\.git/ nocase ascii wide
        $string9_rdpwrap_greyware_tool_keyword = /\/RDPWrap\-v.{0,100}\.zip/ nocase ascii wide
        $string10_rdpwrap_greyware_tool_keyword = /\/res\/rdpwrap\.ini/ nocase ascii wide
        $string11_rdpwrap_greyware_tool_keyword = /\\bin\\RDPConf\.exe/ nocase ascii wide
        $string12_rdpwrap_greyware_tool_keyword = /\\RDP\sWrapper\\/ nocase ascii wide
        $string13_rdpwrap_greyware_tool_keyword = /\\RDPCheck\.exe/ nocase ascii wide
        $string14_rdpwrap_greyware_tool_keyword = /\\RDPWInst\.exe/ nocase ascii wide
        $string15_rdpwrap_greyware_tool_keyword = /\\RDPWInst\-v.{0,100}\.msi/ nocase ascii wide
        $string16_rdpwrap_greyware_tool_keyword = /\\RDPWrap\.cpp/ nocase ascii wide
        $string17_rdpwrap_greyware_tool_keyword = /\\rdpwrap\.dll/ nocase ascii wide
        $string18_rdpwrap_greyware_tool_keyword = /\\rdpwrap\.ini/ nocase ascii wide
        $string19_rdpwrap_greyware_tool_keyword = /\\RDPWrap\.sln/ nocase ascii wide
        $string20_rdpwrap_greyware_tool_keyword = /\\rdpwrap\.txt/ nocase ascii wide
        $string21_rdpwrap_greyware_tool_keyword = /\\rdpwrap\-master/ nocase ascii wide
        $string22_rdpwrap_greyware_tool_keyword = /\\RDPWrapSetup/ nocase ascii wide
        $string23_rdpwrap_greyware_tool_keyword = /\\RDPWrap\-v.{0,100}\.zip/ nocase ascii wide
        $string24_rdpwrap_greyware_tool_keyword = "1232372059db3ecf28cc2609a36b7f20cef2dfe0618770e3ebaa9488bc7fc2de" nocase ascii wide
        $string25_rdpwrap_greyware_tool_keyword = "29E4E73B-EBA6-495B-A76C-FBB462196C64" nocase ascii wide
        $string26_rdpwrap_greyware_tool_keyword = "35a9481ddbed5177431a9ea4bd09468fe987797d7b1231d64942d17eb54ec269" nocase ascii wide
        $string27_rdpwrap_greyware_tool_keyword = "3699b102bf5ad1120ef560ae3036f27c74f6161b62b31fda8087bd7ae1496ee1" nocase ascii wide
        $string28_rdpwrap_greyware_tool_keyword = "9899ffecf141ab4535ec702facbf2b4233903b428b862f3a87e635d09c6244de" nocase ascii wide
        $string29_rdpwrap_greyware_tool_keyword = "aaf7e238a5c0bb2a7956e2fdca9b534f227f7b737641962fb0ed965390ace4c6" nocase ascii wide
        $string30_rdpwrap_greyware_tool_keyword = "f9a82873a1e55bb1b5b8b8781b06799ff665464cff8ce77e07474c089123b643" nocase ascii wide
        $string31_rdpwrap_greyware_tool_keyword = "fed08bd733b8e60b5805007bd01a7bf0d0b1993059bbe319d1179facc6b73361" nocase ascii wide
        $string32_rdpwrap_greyware_tool_keyword = "Initializing RDP Wrapper" nocase ascii wide
        $string33_rdpwrap_greyware_tool_keyword = /\'RDP\sWrapper\sLibrary\sInstaller\sv1\.0\'/ nocase ascii wide
        $string34_rdpwrap_greyware_tool_keyword = /RDP\sWrapper\\RDPConf/ nocase ascii wide
        $string35_rdpwrap_greyware_tool_keyword = "RDPWInst -w" nocase ascii wide
        $string36_rdpwrap_greyware_tool_keyword = /rdpwrap\\.{0,100}\\RDPWInst\./ nocase ascii wide
        $string37_rdpwrap_greyware_tool_keyword = "stascorp/rdpwrap" nocase ascii wide
        
        $string1_FileZilla_greyware_tool_keyword = /\/FileZilla_.{0,100}_sponsored\-setup\.exe/ nocase ascii wide
        $string2_FileZilla_greyware_tool_keyword = /\/FileZilla_Server_.{0,100}\.deb/ nocase ascii wide
        $string3_FileZilla_greyware_tool_keyword = /\\FileZilla_.{0,100}_sponsored\-setup\.exe/ nocase ascii wide
        $string4_FileZilla_greyware_tool_keyword = /\\FILEZILLA_.{0,100}_WIN64_SPONSO\-.{0,100}\.pf/ nocase ascii wide
        $string5_FileZilla_greyware_tool_keyword = /\\FileZilla_.{0,100}\-setup\.exe/ nocase ascii wide
        $string6_FileZilla_greyware_tool_keyword = /\\FileZilla_Server_/ nocase ascii wide
        $string7_FileZilla_greyware_tool_keyword = /\\Program\sFiles\\FileZilla\sFTP\sClient\\/ nocase ascii wide
        $string8_FileZilla_greyware_tool_keyword = /\\Program\sFiles\\FileZilla\sServer/ nocase ascii wide
        $string9_FileZilla_greyware_tool_keyword = /\\Software\\WOW6432Node\\FileZilla\sClient/ nocase ascii wide
        $string10_FileZilla_greyware_tool_keyword = ">FileZilla FTP Client<" nocase ascii wide
        $string11_FileZilla_greyware_tool_keyword = ">FileZilla Server<" nocase ascii wide
        $string12_FileZilla_greyware_tool_keyword = /download\.filezilla\-project\.org/ nocase ascii wide
        $string13_FileZilla_greyware_tool_keyword = /Software\\FileZilla/ nocase ascii wide
        $string14_FileZilla_greyware_tool_keyword = "Win32/FileZilla_BundleInstaller" nocase ascii wide
        
        $string1_processhacker_greyware_tool_keyword = /\/processhacker\-.{0,100}\-bin\.zip/ nocase ascii wide
        $string2_processhacker_greyware_tool_keyword = "/processhacker/files/latest/download" nocase ascii wide
        $string3_processhacker_greyware_tool_keyword = /\\Process\sHacker\s2\\/ nocase ascii wide
        $string4_processhacker_greyware_tool_keyword = /processhacker\-.{0,100}\-sdk\.zip/ nocase ascii wide
        $string5_processhacker_greyware_tool_keyword = /processhacker\-.{0,100}\-setup\.exe/ nocase ascii wide
        $string6_processhacker_greyware_tool_keyword = /processhacker\-.{0,100}\-src\.zip/ nocase ascii wide
        $string7_processhacker_greyware_tool_keyword = /ProcessHacker\.exe/ nocase ascii wide
        $string8_processhacker_greyware_tool_keyword = /ProcessHacker\.sln/ nocase ascii wide
        
        $string22_bash_greyware_tool_keyword = /rm\s\.bash_history/ nocase ascii wide
        $string23_bash_greyware_tool_keyword = /rm\s\/home\/.{0,100}\/\.bash_history/ nocase ascii wide
        $string24_bash_greyware_tool_keyword = /rm\s\/root\/\.bash_history/ nocase ascii wide
        $string25_bash_greyware_tool_keyword = /set\shistory\s\+o/ nocase ascii wide
        $string26_bash_greyware_tool_keyword = /sh\s\>\/dev\/tcp\/.{0,100}\s\<\&1\s2\>\&1/ nocase ascii wide
        $string27_bash_greyware_tool_keyword = /sh\s\-i\s\>\&\s\/dev\/udp\/.{0,100}\/.{0,100}\s0\>\&1/ nocase ascii wide
        $string28_bash_greyware_tool_keyword = /truncate\s\-s0\s.{0,100}bash_history\'/ nocase ascii wide
        $string29_bash_greyware_tool_keyword = "unset HISTFILE" nocase ascii wide
        
        $string1__base64_greyware_tool_keyword = /\|\sbase64\s\-d\s/ nocase ascii wide
        $string2__base64_greyware_tool_keyword = "base64 -d /tmp/" nocase ascii wide
        
        $string1_netstat_greyware_tool_keyword = "netsat -naop" nocase ascii wide
        $string2_netstat_greyware_tool_keyword = "netstat -ano" nocase ascii wide
        $string3_netstat_greyware_tool_keyword = "netstat -ant" nocase ascii wide
        $string4_netstat_greyware_tool_keyword = /NETSTAT\.EXE.{0,100}\s\-ano/ nocase ascii wide
        
        $string1_shell_greyware_tool_keyword = /\/bin\/sh\s\|\snc/ nocase ascii wide
        $string2_shell_greyware_tool_keyword = "/bin/sh -i <&3 >&3 2>&3" nocase ascii wide
        $string3_shell_greyware_tool_keyword = /rm\s\-f\sbackpipe.{0,100}\smknod\s\/tmp\/backpipe\sp\s\&\&\snc\s/ nocase ascii wide
        $string4_shell_greyware_tool_keyword = "sc config WinDefend start= disabled" nocase ascii wide
        $string5_shell_greyware_tool_keyword = "schkconfig off cbdaemon" nocase ascii wide
        $string6_shell_greyware_tool_keyword = "service cbdaemon stop" nocase ascii wide
        $string7_shell_greyware_tool_keyword = /socket\(S.{0,100}PF_INET.{0,100}SOCK_STREAM.{0,100}getprotobyname\(.{0,100}tcp.{0,100}\)\).{0,100}if\(connect\(S.{0,100}sockaddr_in\(\$p.{0,100}inet_aton\(\$i\)\)\)\)/ nocase ascii wide
        $string8_shell_greyware_tool_keyword = /STDIN\-\>fdopen\(\$c.{0,100}r\).{0,100}\$\~\-\>fdopen\(\$c.{0,100}w\).{0,100}system\$_\swhile\<\>/ nocase ascii wide
        $string9_shell_greyware_tool_keyword = /uname\s\-a.{0,100}\sw.{0,100}\sid.{0,100}\s\/bin\/bash\s\-i/ nocase ascii wide
        $string10_shell_greyware_tool_keyword = "setenforce 0" nocase ascii wide
        
        $string1_bcdedit_greyware_tool_keyword = /bcdedit\s\/set\s\{default\}\sbootstatuspolicy\signoreallfailures/ nocase ascii wide
        $string2_bcdedit_greyware_tool_keyword = /bcdedit\s\/set\s\{default\}\srecoveryenabled\sNo/ nocase ascii wide
        $string3_bcdedit_greyware_tool_keyword = /bcdedit.{0,100}\s\/set\s\{default\}\sbootstatuspolicy\signoreallfailures/ nocase ascii wide
        $string4_bcdedit_greyware_tool_keyword = /bcdedit.{0,100}\s\/set\s\{default\}\srecoveryenabled\sNo/ nocase ascii wide
        
        $string1_vssadmin_greyware_tool_keyword = /\.exe\sdelete\sshadows/ nocase ascii wide
        $string2_vssadmin_greyware_tool_keyword = "vssadmin create shadow /for=C:" nocase ascii wide
        $string3_vssadmin_greyware_tool_keyword = /vssadmin\screate\sshadow\s\/for\=C\:.{0,100}\s\\Temp\\.{0,100}\.tmp/ nocase ascii wide
        $string4_vssadmin_greyware_tool_keyword = "vssadmin delete shadows" nocase ascii wide
        $string5_vssadmin_greyware_tool_keyword = "vssadmin list shadows" nocase ascii wide
        $string6_vssadmin_greyware_tool_keyword = /vssadmin.{0,100}\sDelete\sShadows\s\/All\s\/Quiet/ nocase ascii wide
        $string7_vssadmin_greyware_tool_keyword = /vssadmin\.exe\sCreate\sShadow\s\/for\=/ nocase ascii wide
        
        $string1_wbadmin_greyware_tool_keyword = "wbadmin delete backup" nocase ascii wide
        $string2_wbadmin_greyware_tool_keyword = "wbadmin delete catalog -quiet" nocase ascii wide
        $string3_wbadmin_greyware_tool_keyword = "wbadmin DELETE SYSTEMSTATEBACKUP -deleteOldest" nocase ascii wide
        $string4_wbadmin_greyware_tool_keyword = "wbadmin DELETE SYSTEMSTATEBACKUP" nocase ascii wide
        
        $string1_Cmdkey_greyware_tool_keyword = "Cmdkey /list" nocase ascii wide
        
        $string1_psexec_greyware_tool_keyword = /\s\-accepteula\s\-nobanner\s\-d\scmd\.exe\s\/c\s/ nocase ascii wide
        $string2_psexec_greyware_tool_keyword = /\.exe\s\-i\s\-s\scmd\.exe/ nocase ascii wide
        $string3_psexec_greyware_tool_keyword = /\\PsExec\.exe/ nocase ascii wide
        $string4_psexec_greyware_tool_keyword = /\\SOFTWARE\\Sysinternals\\PsExec\\EulaAccepted/ nocase ascii wide
        $string5_psexec_greyware_tool_keyword = /\\Windows\\Prefetch\\PSEXEC/ nocase ascii wide
        $string6_psexec_greyware_tool_keyword = /\\Windows\\PSEXEC\-.{0,100}\.key/ nocase ascii wide
        $string7_psexec_greyware_tool_keyword = /PSEXEC\-.{0,100}\.key/ nocase ascii wide
        $string8_psexec_greyware_tool_keyword = /PsExec\[1\]\.exe/ nocase ascii wide
        $string9_psexec_greyware_tool_keyword = /PsExec64\.exe/ nocase ascii wide
        $string10_psexec_greyware_tool_keyword = "PSEXECSVC" nocase ascii wide
        $string11_psexec_greyware_tool_keyword = /PSEXECSVC\.EXE\-.{0,100}\.pf/ nocase ascii wide
        
        $string1_openssh_portable_greyware_tool_keyword = /\\\\pipe\\\\openssh\-ssh\-agent/ nocase ascii wide
        $string2_openssh_portable_greyware_tool_keyword = /\\OpenSSHTestTasks\\/ nocase ascii wide
        $string3_openssh_portable_greyware_tool_keyword = /\\pipe\\openssh\-ssh\-agent/ nocase ascii wide
        $string4_openssh_portable_greyware_tool_keyword = /\\Software\\OpenSSH\\DefaultShell/ nocase ascii wide
        $string5_openssh_portable_greyware_tool_keyword = /install\-sshd\.ps1/ nocase ascii wide
        $string6_openssh_portable_greyware_tool_keyword = "net start ssh-agent" nocase ascii wide
        $string7_openssh_portable_greyware_tool_keyword = "New-Service -Name sshd" nocase ascii wide
        
        $string1_systeminfo_greyware_tool_keyword = "cmd /c systeminfo" nocase ascii wide
        $string2_systeminfo_greyware_tool_keyword = /cmd\.exe\s\/c\ssysteminfo/ nocase ascii wide
        
        $string1_tightvnc_greyware_tool_keyword = " -service TightVNC Server" nocase ascii wide
        $string2_tightvnc_greyware_tool_keyword = /\.\\TightVNC1/ nocase ascii wide
        $string3_tightvnc_greyware_tool_keyword = /\.\\TightVNC2/ nocase ascii wide
        $string4_tightvnc_greyware_tool_keyword = /\.\\TightVNC3/ nocase ascii wide
        $string5_tightvnc_greyware_tool_keyword = /\/tightvnc\-.{0,100}\.msi/ nocase ascii wide
        $string6_tightvnc_greyware_tool_keyword = /\\mlnhcpkomdeavomsjalt/ nocase ascii wide
        $string7_tightvnc_greyware_tool_keyword = /\\Programs\\TightVNC/ nocase ascii wide
        $string8_tightvnc_greyware_tool_keyword = /\\SOFTWARE\\WOW6432Node\\TightVNC\\/ nocase ascii wide
        $string9_tightvnc_greyware_tool_keyword = /\\TightVNC\sServer/ nocase ascii wide
        $string10_tightvnc_greyware_tool_keyword = /\\tightvnc\-/ nocase ascii wide
        $string11_tightvnc_greyware_tool_keyword = /\\TightVNC_Service_Control/ nocase ascii wide
        $string12_tightvnc_greyware_tool_keyword = /\\TVN_log_pipe_public_name/ nocase ascii wide
        $string13_tightvnc_greyware_tool_keyword = ">TightVNC Viewer<" nocase ascii wide
        $string14_tightvnc_greyware_tool_keyword = /00\:\\\.vnc\\/ nocase ascii wide
        $string15_tightvnc_greyware_tool_keyword = /GlavSoft\sLLC\./ nocase ascii wide
        $string16_tightvnc_greyware_tool_keyword = /HKCR\\\.vnc/ nocase ascii wide
        $string17_tightvnc_greyware_tool_keyword = /program\sfiles\s\(x86\)\\tightvnc\\/ nocase ascii wide
        $string18_tightvnc_greyware_tool_keyword = /ProgramData\\TightVNC/ nocase ascii wide
        $string19_tightvnc_greyware_tool_keyword = "TightVNC Service" nocase ascii wide
        $string20_tightvnc_greyware_tool_keyword = /TightVNC\sWeb\sSite\.url/ nocase ascii wide
        $string21_tightvnc_greyware_tool_keyword = "tvnserver" nocase ascii wide
        $string22_tightvnc_greyware_tool_keyword = /tvnserver\.exe/ nocase ascii wide
        $string23_tightvnc_greyware_tool_keyword = /tvnviewer\.exe/ nocase ascii wide
        $string24_tightvnc_greyware_tool_keyword = /VncViewer\.Config/ nocase ascii wide
        $string25_tightvnc_greyware_tool_keyword = /www\.tightvnc\.com\/download\/.{0,100}\=/ nocase ascii wide
        
        $string1_ssh_greyware_tool_keyword = "bad client public DH value" nocase ascii wide
        $string2_ssh_greyware_tool_keyword = "fatal: buffer_get_string: bad string" nocase ascii wide
        $string3_ssh_greyware_tool_keyword = "Local: crc32 compensation attack" nocase ascii wide
        $string4_ssh_greyware_tool_keyword = "nano /etc/ssh/sshd_config" nocase ascii wide
        $string5_ssh_greyware_tool_keyword = /ssh\.exe\s\-L\s0\.0\.0\.0\:445\:127\.0\.0\.1\:445\s/ nocase ascii wide
        $string6_ssh_greyware_tool_keyword = "vim /etc/ssh/sshd_config" nocase ascii wide
        
        $string1_rmdir__greyware_tool_keyword = /rd\s\/s\s\/q\s\%systemdrive\%\\\$RECYCLE\.BIN/ nocase ascii wide
         
        $string1_advanced_ip_scanner_greyware_tool_keyword = /\.exe\s\/s\:ip_ranges\.txt\s\/f\:scan_results\.txt/ nocase ascii wide
        $string2_advanced_ip_scanner_greyware_tool_keyword = /\\Advanced\sIP\sScanner\.lnk/ nocase ascii wide
        $string3_advanced_ip_scanner_greyware_tool_keyword = /\\advanced_ip_scanner/ nocase ascii wide
        $string4_advanced_ip_scanner_greyware_tool_keyword = /\\Local\\Temp\\Advanced\sIP\sScanner\s2\\/ nocase ascii wide
        $string5_advanced_ip_scanner_greyware_tool_keyword = /\\Program\sFiles\s\(x86\)\\Advanced\sIP\sScanner\\/ nocase ascii wide
        $string6_advanced_ip_scanner_greyware_tool_keyword = /\\Programs\\Advanced\sIP\sScanner\sPortable\\/ nocase ascii wide
        $string7_advanced_ip_scanner_greyware_tool_keyword = /\\Start\sMenu\\Programs\\Advanced\sIP\sScanner\sv2/ nocase ascii wide
        $string8_advanced_ip_scanner_greyware_tool_keyword = ">Advanced IP Scanner Setup<" nocase ascii wide
        $string9_advanced_ip_scanner_greyware_tool_keyword = ">Advanced IP Scanner<" nocase ascii wide
        $string10_advanced_ip_scanner_greyware_tool_keyword = "26d5748ffe6bd95e3fee6ce184d388a1a681006dc23a0f08d53c083c593c193b" nocase ascii wide
        $string12_advanced_ip_scanner_greyware_tool_keyword = "Advanced IP Scanner" nocase ascii wide
        $string13_advanced_ip_scanner_greyware_tool_keyword = /Advanced_IP_Scanner.{0,100}\.exe/ nocase ascii wide
        $string14_advanced_ip_scanner_greyware_tool_keyword = /advanced_ip_scanner_console\.exe/ nocase ascii wide
        $string15_advanced_ip_scanner_greyware_tool_keyword = /https\:\/\/download\.advanced\-ip\-scanner\.com\/download\/files\/.{0,100}\.exe/ nocase ascii wide
        
        $string1_myexternalip_com_greyware_tool_keyword = /https\:\/\/myexternalip\.com\/raw/ nocase ascii wide
        
        $string1_dd_greyware_tool_keyword = "dd if=/dev/nul" nocase ascii wide
        $string2_dd_greyware_tool_keyword = "dd if=/dev/zero" nocase ascii wide
        
        $string1_TelegramRAT_greyware_tool_keyword = /https\:\/\/api\.telegram\.org\/bot.{0,100}\/sendMessage/ nocase ascii wide
        
        $string1___greyware_tool_keyword = " ecivreS-potS" nocase ascii wide
        $string2___greyware_tool_keyword = " gifnoc cs" nocase ascii wide
        $string3___greyware_tool_keyword = " noitcetorPAUP" nocase ascii wide
        $string4___greyware_tool_keyword = "%tooRmetsyS%" nocase ascii wide
        $string5___greyware_tool_keyword = /\.\.\\\.\.\\\.\.\\\.\.\\\.\.\\\.\.\\Windows\\System32\\cmd\.exe/ nocase ascii wide
        $string6___greyware_tool_keyword = /\/keygen\.exe/ nocase ascii wide
        $string7___greyware_tool_keyword = /\/PAYMENTS\.exe/ nocase ascii wide
        $string8___greyware_tool_keyword = /\\1\.bat/ nocase ascii wide
        $string9___greyware_tool_keyword = /\\1\.dll/ nocase ascii wide
        $string10___greyware_tool_keyword = /\\1\.exe/ nocase ascii wide
        $string11___greyware_tool_keyword = /\\2\.bat/ nocase ascii wide
        $string12___greyware_tool_keyword = /\\2\.dll/ nocase ascii wide
        $string13___greyware_tool_keyword = /\\2\.exe/ nocase ascii wide
        $string14___greyware_tool_keyword = /\\3\.bat/ nocase ascii wide
        $string15___greyware_tool_keyword = /\\3\.dll/ nocase ascii wide
        $string16___greyware_tool_keyword = /\\3\.exe/ nocase ascii wide
        $string17___greyware_tool_keyword = /\\4\.bat/ nocase ascii wide
        $string18___greyware_tool_keyword = /\\4\.dll/ nocase ascii wide
        $string19___greyware_tool_keyword = /\\4\.exe/ nocase ascii wide
        $string20___greyware_tool_keyword = /\\5\.bat/ nocase ascii wide
        $string21___greyware_tool_keyword = /\\5\.dll/ nocase ascii wide
        $string22___greyware_tool_keyword = /\\5\.exe/ nocase ascii wide
        $string23___greyware_tool_keyword = /\\6\.bat/ nocase ascii wide
        $string24___greyware_tool_keyword = /\\6\.dll/ nocase ascii wide
        $string25___greyware_tool_keyword = /\\6\.exe/ nocase ascii wide
        $string26___greyware_tool_keyword = /\\7\.bat/ nocase ascii wide
        $string27___greyware_tool_keyword = /\\7\.dll/ nocase ascii wide
        $string28___greyware_tool_keyword = /\\7\.exe/ nocase ascii wide
        $string29___greyware_tool_keyword = /\\8\.bat/ nocase ascii wide
        $string30___greyware_tool_keyword = /\\8\.dll/ nocase ascii wide
        $string31___greyware_tool_keyword = /\\8\.exe/ nocase ascii wide
        $string32___greyware_tool_keyword = /\\9\.bat/ nocase ascii wide
        $string33___greyware_tool_keyword = /\\9\.dll/ nocase ascii wide
        $string34___greyware_tool_keyword = /\\9\.exe/ nocase ascii wide
        $string35___greyware_tool_keyword = /\\AppData\\Roaming\\Microsoft\\Windows\\Start\sMenu\\Programs\\Startup\\.{0,100}\.bat/ nocase ascii wide
        $string36___greyware_tool_keyword = /\\AppData\\Roaming\\Microsoft\\Windows\\Start\sMenu\\Programs\\Startup\\.{0,100}\.cmd/ nocase ascii wide
        $string37___greyware_tool_keyword = /\\AppData\\Roaming\\Microsoft\\Windows\\Start\sMenu\\Programs\\Startup\\.{0,100}\.hta/ nocase ascii wide
        $string38___greyware_tool_keyword = /\\AppData\\Roaming\\Microsoft\\Windows\\Start\sMenu\\Programs\\Startup\\.{0,100}\.ps1/ nocase ascii wide
        $string39___greyware_tool_keyword = /\\AppData\\Roaming\\Microsoft\\Windows\\Start\sMenu\\Programs\\Startup\\.{0,100}\.vbs/ nocase ascii wide
        $string40___greyware_tool_keyword = /\\keygen\.exe/ nocase ascii wide
        $string41___greyware_tool_keyword = /\\PAYMENT\.hta/ nocase ascii wide
        $string42___greyware_tool_keyword = /\\PAYMENT\.hta/ nocase ascii wide
        $string43___greyware_tool_keyword = /\\PAYMENTS\.exe/ nocase ascii wide
        $string44___greyware_tool_keyword = /c\/\sexe\.dmc/ nocase ascii wide
        $string45___greyware_tool_keyword = /c\:\\.{0,100}\\\\u0.{0,100}\\\\u0.{0,100}\\\\u0.{0,100}\\\\u0/ nocase ascii wide
        $string46___greyware_tool_keyword = "delbasiD epyTputratS- " nocase ascii wide
        $string47___greyware_tool_keyword = "ecnereferPpM-teS" nocase ascii wide
        $string48___greyware_tool_keyword = "eliforPllaweriFteN-teS" nocase ascii wide
        $string49___greyware_tool_keyword = /exe\.23lldnur/ nocase ascii wide
        $string50___greyware_tool_keyword = /exe\.erolpxei/ nocase ascii wide
        $string51___greyware_tool_keyword = /exe\.rerolpxe/ nocase ascii wide
        $string52___greyware_tool_keyword = /exe\.ssasl/ nocase ascii wide
        $string53___greyware_tool_keyword = /exe\.tsohcvs/ nocase ascii wide
        $string54___greyware_tool_keyword = "gnirotinoMemitlaeRelbasiD" nocase ascii wide
        $string55___greyware_tool_keyword = /https\:\/\/requestbin\.net\/r\// nocase ascii wide
        $string56___greyware_tool_keyword = "llawerifvda hsten" nocase ascii wide
        $string57___greyware_tool_keyword = /niB\.elcyceR\$/ nocase ascii wide
        $string58___greyware_tool_keyword = "teSlortnoCtnerruC" nocase ascii wide
        $string59___greyware_tool_keyword = /https\:\/\/.{0,100}\.xyz\/.{0,100}\.ps1/ nocase ascii wide 
        
        $string1_Ammyy_Admin_greyware_tool_keyword = /\\aa_nts\.dll/ nocase ascii wide
        $string2_Ammyy_Admin_greyware_tool_keyword = /\\AA_v3\.exe/ nocase ascii wide
        $string3_Ammyy_Admin_greyware_tool_keyword = /\\AA_v3\.log/ nocase ascii wide
        $string4_Ammyy_Admin_greyware_tool_keyword = /\\AMMYY\\access\.log/ nocase ascii wide
        $string5_Ammyy_Admin_greyware_tool_keyword = /\\ControlSet001\\Control\\SafeBoot\\Network\\AmmyyAdmin_/ nocase ascii wide
        $string6_Ammyy_Admin_greyware_tool_keyword = /\\ProgramData\\AMMYY\\/ nocase ascii wide
        $string7_Ammyy_Admin_greyware_tool_keyword = /\\SOFTWARE\\Ammyy\\Admin/ nocase ascii wide
        $string8_Ammyy_Admin_greyware_tool_keyword = /AA_v3\.exe.{0,100}\s\-elevated/ nocase ascii wide
        $string9_Ammyy_Admin_greyware_tool_keyword = /AA_v3\.exe.{0,100}\s\-service\s\-lunch/ nocase ascii wide
        $string10_Ammyy_Admin_greyware_tool_keyword = "Ammyy Admin" nocase ascii wide
        $string11_Ammyy_Admin_greyware_tool_keyword = "Ammyy LLC" nocase ascii wide
        $string12_Ammyy_Admin_greyware_tool_keyword = /AMMYY_Admin\.exe/ nocase ascii wide
        $string13_Ammyy_Admin_greyware_tool_keyword = /rl\.ammyy\.com\// nocase ascii wide
        $string14_Ammyy_Admin_greyware_tool_keyword = /SPR\/Ammyy\.R/ nocase ascii wide
        $string15_Ammyy_Admin_greyware_tool_keyword = /Win32\.PUA\.AmmyyAdmin/ nocase ascii wide
        $string16_Ammyy_Admin_greyware_tool_keyword = /www\.ammyy\.com\/files\/v/ nocase ascii wide
        
        $string1_github_greyware_tool_keyword = /\/github\.com.{0,100}\.exe\?raw\=true/ nocase ascii wide
        $string2_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/archive\/refs\/tags\/.{0,100}\.zip/ nocase ascii wide
        $string3_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.7z/ nocase ascii wide
        $string4_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.apk/ nocase ascii wide
        $string5_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.app/ nocase ascii wide
        $string6_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.as/ nocase ascii wide
        $string7_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.asc/ nocase ascii wide
        $string8_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.asp/ nocase ascii wide
        $string9_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.bash/ nocase ascii wide
        $string10_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.bat/ nocase ascii wide
        $string11_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.beacon/ nocase ascii wide
        $string12_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.bin/ nocase ascii wide
        $string13_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.bpl/ nocase ascii wide
        $string14_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.c/ nocase ascii wide
        $string15_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.cer/ nocase ascii wide
        $string16_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.cmd/ nocase ascii wide
        $string17_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.com/ nocase ascii wide
        $string18_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.cpp/ nocase ascii wide
        $string19_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.crt/ nocase ascii wide
        $string20_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.cs/ nocase ascii wide
        $string21_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.csh/ nocase ascii wide
        $string22_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.dat/ nocase ascii wide
        $string23_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.dll/ nocase ascii wide
        $string24_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.docm/ nocase ascii wide
        $string25_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.dos/ nocase ascii wide
        $string26_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.exe/ nocase ascii wide
        $string27_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.go/ nocase ascii wide
        $string28_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.gz/ nocase ascii wide
        $string29_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.hta/ nocase ascii wide
        $string30_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.iso/ nocase ascii wide
        $string31_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.jar/ nocase ascii wide
        $string32_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.js/ nocase ascii wide
        $string33_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.lnk/ nocase ascii wide
        $string34_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.log/ nocase ascii wide
        $string35_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.mac/ nocase ascii wide
        $string36_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.mam/ nocase ascii wide
        $string37_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.msi/ nocase ascii wide
        $string38_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.msp/ nocase ascii wide
        $string39_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.nexe/ nocase ascii wide
        $string40_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.nim/ nocase ascii wide
        $string41_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.otm/ nocase ascii wide
        $string42_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.out/ nocase ascii wide
        $string43_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.ova/ nocase ascii wide
        $string44_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.pem/ nocase ascii wide
        $string45_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.pfx/ nocase ascii wide
        $string46_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.pl/ nocase ascii wide
        $string47_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.plx/ nocase ascii wide
        $string48_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.pm/ nocase ascii wide
        $string49_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.ppk/ nocase ascii wide
        $string50_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.ps1/ nocase ascii wide
        $string51_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.psm1/ nocase ascii wide
        $string52_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.pub/ nocase ascii wide
        $string53_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.py/ nocase ascii wide
        $string54_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.pyc/ nocase ascii wide
        $string55_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.pyo/ nocase ascii wide
        $string56_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.rar/ nocase ascii wide
        $string57_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.raw/ nocase ascii wide
        $string58_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.reg/ nocase ascii wide
        $string59_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.rgs/ nocase ascii wide
        $string60_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.RGS/ nocase ascii wide
        $string61_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.run/ nocase ascii wide
        $string62_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.scpt/ nocase ascii wide
        $string63_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.script/ nocase ascii wide
        $string64_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.sct/ nocase ascii wide
        $string65_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.sh/ nocase ascii wide
        $string66_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.ssh/ nocase ascii wide
        $string67_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.sys/ nocase ascii wide
        $string68_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.teamserver/ nocase ascii wide
        $string69_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.temp/ nocase ascii wide
        $string70_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.tgz/ nocase ascii wide
        $string71_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.tmp/ nocase ascii wide
        $string72_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.vb/ nocase ascii wide
        $string73_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.vbs/ nocase ascii wide
        $string74_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.vbscript/ nocase ascii wide
        $string75_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.ws/ nocase ascii wide
        $string76_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.wsf/ nocase ascii wide
        $string77_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.wsh/ nocase ascii wide
        $string78_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.X86/ nocase ascii wide
        $string79_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.X86_64/ nocase ascii wide
        $string80_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.xlam/ nocase ascii wide
        $string81_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.xlm/ nocase ascii wide
        $string82_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.xlsm/ nocase ascii wide
        $string83_github_greyware_tool_keyword = /\/github\.com\/.{0,100}\/raw\/main\/.{0,100}\.zip/ nocase ascii wide
        $string84_github_greyware_tool_keyword = /codeload\.github\.com\// nocase ascii wide
        $string85_github_greyware_tool_keyword = /objects\.githubusercontent\.com\/github\-production\-release\-asset\-/ nocase ascii wide
        $string86_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.7z/ nocase ascii wide
        $string87_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.apk/ nocase ascii wide
        $string88_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.app/ nocase ascii wide
        $string89_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.as/ nocase ascii wide
        $string90_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.asc/ nocase ascii wide
        $string91_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.asp/ nocase ascii wide
        $string92_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.bash/ nocase ascii wide
        $string93_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.bat/ nocase ascii wide
        $string94_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.beacon/ nocase ascii wide
        $string95_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.bin/ nocase ascii wide
        $string96_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.bpl/ nocase ascii wide
        $string97_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.c/ nocase ascii wide
        $string98_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.cer/ nocase ascii wide
        $string99_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.cmd/ nocase ascii wide
        $string100_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.com/ nocase ascii wide
        $string101_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.cpp/ nocase ascii wide
        $string102_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.crt/ nocase ascii wide
        $string103_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.cs/ nocase ascii wide
        $string104_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.csh/ nocase ascii wide
        $string105_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.dat/ nocase ascii wide
        $string106_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.dll/ nocase ascii wide
        $string107_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.docm/ nocase ascii wide
        $string108_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.dos/ nocase ascii wide
        $string109_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.exe/ nocase ascii wide
        $string110_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.go/ nocase ascii wide
        $string111_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.gz/ nocase ascii wide
        $string112_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.hta/ nocase ascii wide
        $string113_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.iso/ nocase ascii wide
        $string114_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.jar/ nocase ascii wide
        $string115_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.js/ nocase ascii wide
        $string116_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.lnk/ nocase ascii wide
        $string117_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.log/ nocase ascii wide
        $string118_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.mac/ nocase ascii wide
        $string119_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.mam/ nocase ascii wide
        $string120_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.msi/ nocase ascii wide
        $string121_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.msp/ nocase ascii wide
        $string122_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.nexe/ nocase ascii wide
        $string123_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.nim/ nocase ascii wide
        $string124_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.otm/ nocase ascii wide
        $string125_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.out/ nocase ascii wide
        $string126_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.ova/ nocase ascii wide
        $string127_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.pem/ nocase ascii wide
        $string128_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.pfx/ nocase ascii wide
        $string129_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.pl/ nocase ascii wide
        $string130_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.plx/ nocase ascii wide
        $string131_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.pm/ nocase ascii wide
        $string132_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.ppk/ nocase ascii wide
        $string133_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.ps1/ nocase ascii wide
        $string134_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.psm1/ nocase ascii wide
        $string135_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.pub/ nocase ascii wide
        $string136_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.py/ nocase ascii wide
        $string137_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.pyc/ nocase ascii wide
        $string138_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.pyo/ nocase ascii wide
        $string139_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.rar/ nocase ascii wide
        $string140_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.raw/ nocase ascii wide
        $string141_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.reg/ nocase ascii wide
        $string142_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.rgs/ nocase ascii wide
        $string143_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.RGS/ nocase ascii wide
        $string144_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.run/ nocase ascii wide
        $string145_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.scpt/ nocase ascii wide
        $string146_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.script/ nocase ascii wide
        $string147_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.sct/ nocase ascii wide
        $string148_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.sh/ nocase ascii wide
        $string149_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.ssh/ nocase ascii wide
        $string150_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.sys/ nocase ascii wide
        $string151_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.teamserver/ nocase ascii wide
        $string152_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.temp/ nocase ascii wide
        $string153_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.tgz/ nocase ascii wide
        $string154_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.tmp/ nocase ascii wide
        $string155_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.vb/ nocase ascii wide
        $string156_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.vbs/ nocase ascii wide
        $string157_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.vbscript/ nocase ascii wide
        $string158_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.ws/ nocase ascii wide
        $string159_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.wsf/ nocase ascii wide
        $string160_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.wsh/ nocase ascii wide
        $string161_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.X86/ nocase ascii wide
        $string162_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.X86_64/ nocase ascii wide
        $string163_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.xlam/ nocase ascii wide
        $string164_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.xlm/ nocase ascii wide
        $string165_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.xlsm/ nocase ascii wide
        $string166_github_greyware_tool_keyword = /raw\.githubusercontent\.com.{0,100}\.zip/ nocase ascii wide
        
        $string1_textbin_net_greyware_tool_keyword = /https\:\/\/textbin\.net\/raw\// nocase ascii wide
        
        $string1_iptables_greyware_tool_keyword = "chkconfig off ip6tables" nocase ascii wide
        $string2_iptables_greyware_tool_keyword = "chkconfig off iptables" nocase ascii wide
        $string3_iptables_greyware_tool_keyword = "service ip6tables stop" nocase ascii wide
        $string4_iptables_greyware_tool_keyword = "service iptables stop" nocase ascii wide
        
        $string1_esxcli_greyware_tool_keyword = "esxcli network firewall set -enabled f" nocase ascii wide
        $string2_esxcli_greyware_tool_keyword = "esxcli system account add" nocase ascii wide
        $string3_esxcli_greyware_tool_keyword = "esxcli system account remove" nocase ascii wide
        $string4_esxcli_greyware_tool_keyword = /esxcli\ssystem\saccount\sset\s\-i\s.{0,100}\s\-s\st/ nocase ascii wide
        $string5_esxcli_greyware_tool_keyword = "esxcli system auditrecords local disable" nocase ascii wide
        $string6_esxcli_greyware_tool_keyword = "esxcli system permission list" nocase ascii wide
        $string7_esxcli_greyware_tool_keyword = "esxcli system settings encryption set - require-exec-installed-only=F" nocase ascii wide
        $string8_esxcli_greyware_tool_keyword = "esxcli system settings encryption set - require-secure-boot=F" nocase ascii wide
        $string9_esxcli_greyware_tool_keyword = "esxcli system settings kernel set -s execInstalledOnly -v F" nocase ascii wide
        $string10_esxcli_greyware_tool_keyword = "esxcli vm process kill " nocase ascii wide
        $string11_esxcli_greyware_tool_keyword = "esxcli vm process list" nocase ascii wide
        
        $string1_xmrig_greyware_tool_keyword = /\s\sxmrig\.exe/ nocase ascii wide
        $string2_xmrig_greyware_tool_keyword = " c3pool_miner" nocase ascii wide
        $string3_xmrig_greyware_tool_keyword = /\s\-\-coin\s.{0,100}\-\-nicehash\s/ nocase ascii wide
        $string4_xmrig_greyware_tool_keyword = " --coin=monero" nocase ascii wide
        $string5_xmrig_greyware_tool_keyword = /\s\-\-config\=.{0,100}c3pool.{0,100}config_background\.json/ nocase ascii wide
        $string6_xmrig_greyware_tool_keyword = " --donate-level=" nocase ascii wide
        $string7_xmrig_greyware_tool_keyword = " install c3pool_miner " nocase ascii wide
        $string8_xmrig_greyware_tool_keyword = /\s\-\-nicehash\s.{0,100}\-\-coin\s/ nocase ascii wide
        $string9_xmrig_greyware_tool_keyword = " set xmrig Type SERVICE_WIN32_OWN_PROCESS" nocase ascii wide
        $string10_xmrig_greyware_tool_keyword = /\%USERPROFILE\%\\\\nssm\.zip/ nocase ascii wide
        $string11_xmrig_greyware_tool_keyword = /\/xmrig\-.{0,100}\-gcc\-win64\.zip/ nocase ascii wide
        $string12_xmrig_greyware_tool_keyword = /\/xmrig\.exe/ nocase ascii wide
        $string13_xmrig_greyware_tool_keyword = /\/xmrig\.git/ nocase ascii wide
        $string14_xmrig_greyware_tool_keyword = /\\c3pool\\\\miner\.bat/ nocase ascii wide
        $string15_xmrig_greyware_tool_keyword = /\\c3pool\\config\.json/ nocase ascii wide
        $string16_xmrig_greyware_tool_keyword = /\\WinRing0x64\.sys/ nocase ascii wide
        $string17_xmrig_greyware_tool_keyword = /\\xmrig\-.{0,100}\-gcc\-win64\.zip/ nocase ascii wide
        $string18_xmrig_greyware_tool_keyword = /\\xmrig\.exe/ nocase ascii wide
        $string19_xmrig_greyware_tool_keyword = /\\xmrig\.log/ nocase ascii wide
        $string20_xmrig_greyware_tool_keyword = /\\xmrig_setup\\/ nocase ascii wide
        $string21_xmrig_greyware_tool_keyword = /\\xmrig\-6\.20\.0/ nocase ascii wide
        $string22_xmrig_greyware_tool_keyword = /\\xmrig\-master/ nocase ascii wide
        $string23_xmrig_greyware_tool_keyword = /\]\sCreating\sc3pool_miner\sservice/ nocase ascii wide
        $string24_xmrig_greyware_tool_keyword = /\]\sLooking\sfor\sthe\slatest\sversion\sof\sMonero\sminer/ nocase ascii wide
        $string25_xmrig_greyware_tool_keyword = /\]\sRemoving\sprevious\sc3pool\sminer\s/ nocase ascii wide
        $string26_xmrig_greyware_tool_keyword = /\]\sRunning\sminer\sin\sthe\sbackground/ nocase ascii wide
        $string27_xmrig_greyware_tool_keyword = "08384f3f05ad85b2aa935dbd2e46a053cb0001b28bbe593dde2a8c4b822c2a7d" nocase ascii wide
        $string28_xmrig_greyware_tool_keyword = "0tZG9uYXRlLWxldmVsP" nocase ascii wide
        $string29_xmrig_greyware_tool_keyword = "3b5cbf0dddc3ef7e3af7d783baef315bf47be6ce11ff83455a2165befe6711f5" nocase ascii wide
        $string30_xmrig_greyware_tool_keyword = "4fe9647d6a8bf4790df0277283f9874385e0cd05f3008406ca5624aba8d78924" nocase ascii wide
        $string31_xmrig_greyware_tool_keyword = "5575c76987333427f74263e090910eae45817f0ede6b452d645fd5f9951210c9" nocase ascii wide
        $string32_xmrig_greyware_tool_keyword = "5a6e7d5c10789763b0b06442dbc7f723f8ea9aec1402abedf439c6801a8d86f2" nocase ascii wide
        $string33_xmrig_greyware_tool_keyword = "99e3e313b62bb8b55e2637fc14a78adb6f33632a3c722486416252e2630cfdf6" nocase ascii wide
        $string34_xmrig_greyware_tool_keyword = "C3Pool mining setup script v" nocase ascii wide
        $string35_xmrig_greyware_tool_keyword = "C3Pool/xmrig_setup" nocase ascii wide
        $string36_xmrig_greyware_tool_keyword = "c3pool_miner service" nocase ascii wide
        $string37_xmrig_greyware_tool_keyword = /c3pool_miner\.bat/ nocase ascii wide
        $string38_xmrig_greyware_tool_keyword = /c3pool_miner\.service/ nocase ascii wide
        $string39_xmrig_greyware_tool_keyword = /c3pool_miner\.sh/ nocase ascii wide
        $string40_xmrig_greyware_tool_keyword = /c3pool_miner\\/ nocase ascii wide
        $string41_xmrig_greyware_tool_keyword = "cpulimit -e xmrig " nocase ascii wide
        $string42_xmrig_greyware_tool_keyword = "dd7fef5e3594eb18dd676e550e128d4b64cc5a469ff6954a677dc414265db468" nocase ascii wide
        $string43_xmrig_greyware_tool_keyword = "Description=Monero miner service" nocase ascii wide
        $string44_xmrig_greyware_tool_keyword = /donate\.ssl\.xmrig\.com/ nocase ascii wide
        $string45_xmrig_greyware_tool_keyword = /donate\.v2\.xmrig\.com\:3333/ nocase ascii wide
        $string46_xmrig_greyware_tool_keyword = /donate\.xmrig\.com/ nocase ascii wide
        $string47_xmrig_greyware_tool_keyword = /Downloading.{0,100}\%MINER_LOCATION\%/ nocase ascii wide
        $string48_xmrig_greyware_tool_keyword = "e1ff2208b3786cac801ffb470b9475fbb3ced74eb503bfde7aa7f22af113989d" nocase ascii wide
        $string49_xmrig_greyware_tool_keyword = /fee\.xmrig\.com/ nocase ascii wide
        $string50_xmrig_greyware_tool_keyword = "ff6e67d725ee64b4607dc6490a706dc9234c708cff814477de52d3beb781c6a1" nocase ascii wide
        $string51_xmrig_greyware_tool_keyword = /github.{0,100}\/xmrig\/xmrig/ nocase ascii wide
        $string52_xmrig_greyware_tool_keyword = /gpg_keys\/xmrig\.asc/ nocase ascii wide
        $string53_xmrig_greyware_tool_keyword = /https\:\/\/c3pool\.com\/\#\// nocase ascii wide
        $string54_xmrig_greyware_tool_keyword = "killall xmrig" nocase ascii wide
        $string55_xmrig_greyware_tool_keyword = "LS1kb25hdGUtbGV2ZWw9" nocase ascii wide
        $string56_xmrig_greyware_tool_keyword = "mining in background will be started using your startup directory script and only work when your are logged in this host" nocase ascii wide
        $string57_xmrig_greyware_tool_keyword = /Mining\swill\shappen\sto\s.{0,100}\swallet/ nocase ascii wide
        $string58_xmrig_greyware_tool_keyword = "Monero miner is already running in the background" nocase ascii wide
        $string59_xmrig_greyware_tool_keyword = "nssm set xmrig AppNoConsole 1" nocase ascii wide
        $string60_xmrig_greyware_tool_keyword = /offline_miner_setup\.zip/ nocase ascii wide
        $string61_xmrig_greyware_tool_keyword = /randomx\.xmrig\.com/ nocase ascii wide
        $string62_xmrig_greyware_tool_keyword = "set xmrig start" nocase ascii wide
        $string63_xmrig_greyware_tool_keyword = "setup and run in background Monero CPU miner" nocase ascii wide
        $string64_xmrig_greyware_tool_keyword = /solo_mine_example\.cmd/ nocase ascii wide
        $string65_xmrig_greyware_tool_keyword = /src\/xmrig\.cpp/ nocase ascii wide
        $string66_xmrig_greyware_tool_keyword = /src\\xmrig\.cpp/ nocase ascii wide
        $string67_xmrig_greyware_tool_keyword = "start doing stuff: preparing miner" nocase ascii wide
        $string68_xmrig_greyware_tool_keyword = /support\@c3pool\.com/ nocase ascii wide
        $string69_xmrig_greyware_tool_keyword = /WinRing0.{0,100}WinRing0x64\.sys/ nocase ascii wide
        $string70_xmrig_greyware_tool_keyword = /xmrig\-.{0,100}\-bionic\-x64\.tar\.gz/ nocase ascii wide
        $string71_xmrig_greyware_tool_keyword = /xmrig\-.{0,100}\-focal\-x64\.tar\.gz/ nocase ascii wide
        $string72_xmrig_greyware_tool_keyword = /xmrig\-.{0,100}\-freebsd\-static\-x64\.tar\.gz/ nocase ascii wide
        $string73_xmrig_greyware_tool_keyword = /xmrig\-.{0,100}\-gcc\-win64\.zip/ nocase ascii wide
        $string74_xmrig_greyware_tool_keyword = /xmrig\-.{0,100}\-linux\-static\-x64\.tar\.gz/ nocase ascii wide
        $string75_xmrig_greyware_tool_keyword = /xmrig\-.{0,100}\-linux\-x64\.tar\.gz/ nocase ascii wide
        $string76_xmrig_greyware_tool_keyword = /xmrig\-.{0,100}\-macos\-arm64\.tar\.gz/ nocase ascii wide
        $string77_xmrig_greyware_tool_keyword = /xmrig\-.{0,100}\-macos\-x64\.tar\.gz/ nocase ascii wide
        $string78_xmrig_greyware_tool_keyword = /xmrig\-.{0,100}\-msvc\-win64\.zip/ nocase ascii wide
        $string79_xmrig_greyware_tool_keyword = /xmrig\.exe\s\-/ nocase ascii wide
        $string80_xmrig_greyware_tool_keyword = /xmrig\.service/ nocase ascii wide
        $string81_xmrig_greyware_tool_keyword = /xmrig\.tar\.gz/ nocase ascii wide
        $string82_xmrig_greyware_tool_keyword = /xmrig\.zip/ nocase ascii wide
        $string83_xmrig_greyware_tool_keyword = /xmrminer\.cc/ nocase ascii wide
        $string84_xmrig_greyware_tool_keyword = /xmrpool\.de/ nocase ascii wide
        $string85_xmrig_greyware_tool_keyword = /xmrpool\.eu/ nocase ascii wide
        $string86_xmrig_greyware_tool_keyword = /xmrpool\.eu\:3333/ nocase ascii wide
        $string87_xmrig_greyware_tool_keyword = /xmrpool\.me/ nocase ascii wide
        $string88_xmrig_greyware_tool_keyword = /xmrpool\.net/ nocase ascii wide
        $string89_xmrig_greyware_tool_keyword = /xmrpool\.xyz/ nocase ascii wide
        
        $metadata_regex_import = /\bimport\s+[a-zA-Z0-9_.]+\b/ nocase
        $metadata_regex_function = /function\s+[a-zA-Z_][a-zA-Z0-9_]*\(/ nocase ascii
        $metadata_regex_php = /<\?php/ nocase ascii
        $metadata_regex_createobject = /(CreateObject|WScript\.)/ nocase ascii
        $metadata_regex_script = /<script\b/ nocase ascii
        $metadata_regex_javascript = /(let\s|const\s|function\s|document\.|console\.)/ nocase ascii
        $metadata_regex_powershell = /(Write-Host|Get-[a-zA-Z]+|Invoke-|param\(|\.SYNOPSIS)/ nocase ascii
        $metadata_regex_batch = /@(echo\s|call\s|set\s|goto\s|if\s|for\s|rem\s)/ nocase ascii
        $metadata_regex_shebang = /^#!\// nocase ascii

    condition:
        (((filesize < 20MB and (uint16(0) == 0x5a4d or uint16(0) == 0x457f or uint32be(0) == 0x7f454c46 or uint16(0) == 0xfeca or uint16(0) == 0xfacf or uint32(0) == 0xbebafeca or uint32(0) == 0x504B0304 or uint32(0) == 0xCAFEBABE or uint32(0) == 0x4D534346 or uint32(0) == 0xD0CF11E0 or uint16(0) == 0x2321 or uint16(0) == 0x3c3f)) and any of ($string*)) or (filesize < 2MB and (any of ($string*) and for any of ($metadata_regex_*) : ( @ <= 20000 ))))
  
}
